spring:
  application:
    name: rivalia
  webflux:
    base-path:  /api/v1
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tournament
    username: emerlive
    password: 37a71925
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health, liveness, readiness
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true